package storm.twitter;

import java.util.Map;

import backtype.storm.task.ShellBolt;
import backtype.storm.topology.IRichBolt;
import backtype.storm.topology.OutputFieldsDeclarer;
import backtype.storm.tuple.Fields;

public class GetTweetsBolt extends ShellBolt implements IRichBolt {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 6545122122040077036L;
	
	public GetTweetsBolt() {
		super("python2.7", "python/twitter_storm/get_tweets_bolt.py");
	}

	@Override
	public void declareOutputFields(OutputFieldsDeclarer declarer) {
		declarer.declare(new Fields(TopologyFields.AUTHOR_SCREEN_NAME, TopologyFields.CREATED_AT,
				TopologyFields.FAV_COUNT, TopologyFields.HASHTAGS_TEXTS, TopologyFields.IN_REPLY_TO_SCREEN_NAME, 
				TopologyFields.LANG, TopologyFields.RETWEET_COUNT, TopologyFields.RETWEETED, 
				TopologyFields.SOURCE, TopologyFields.PLACE_FULL_NAME, TopologyFields.POSSIBLY_SENSITIVE,
				TopologyFields.TEXT, TopologyFields.TOPIC_NAME));
	}

	@Override
	public Map<String, Object> getComponentConfiguration() {
		// TODO Auto-generated method stub
		return null;
	}
}
