package storm.twitter;

import java.util.Map;

import backtype.storm.task.ShellBolt;
import backtype.storm.topology.IRichBolt;
import backtype.storm.topology.OutputFieldsDeclarer;
import backtype.storm.tuple.Fields;

public class TrendsBolt extends ShellBolt implements IRichBolt {
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 1239454072915556852L;

	public TrendsBolt() {
		super("python2.7", "python/trends_bolt.py");
	}
	
	@Override
	public void declareOutputFields(OutputFieldsDeclarer declarer) {
		declarer.declare(new Fields(TopologyFields.PLACE, TopologyFields.TOPIC_NAME, TopologyFields.TWITTER_QUERY));
	}

	@Override
	public Map<String, Object> getComponentConfiguration() {
		return null;
	}
}
